config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "mentions_legales", to: "pages#mentions_legales"

  resources :leads, only: [:create]

  resources :admin, only: [:index], controller: "admin/dashboard"
  resources :articles, only: [:index, :show]


  namespace :admin do 
    resources :leads, only: [:index, :new, :create, :edit, :update, :show, :destroy]
    resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :testimonies, only: [:index, :show, :new, :create, :destroy, :edit, :update]
    resources :trusted_customers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end 
end

app/models/article.rb
class Article < ApplicationRecord
  has_many_attached :photos

  has_rich_text :content

  validates :title, presence: true
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::DashboardController

  def index
    if params[:search]
      @articles = Article.where("title ILIKE ?", "%#{params[:search]}%")
    else
      @articles = Article.all.order('created_at DESC')
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to admin_articles_path, notice: "Article créé avec succès."
    else
      render :new, alert: "Veuillez vérifier les erreurs ci-dessous.", status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if params[:article][:photos] == [""] || params[:article][:photos].nil?
      update_params = article_params.except(:photos)
    else
      update_params = article_params
    end
  
    if @article.update(update_params)
      redirect_to admin_articles_path, notice: "Article modifié avec succès."
    else
      render :edit, alert: "Veuillez vérifier les erreurs ci-dessous.", status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to admin_articles_path, notice: "Article supprimé avec succès."
  end 

  private 

  def require_admin
    unless current_user.admin?
      redirect_to root_path, alert: "Vous n'êtes pas autorisé à accéder à cette page."
    end
  end

  def article_params
    params.require(:article).permit(:title, :content, :intro_text, :category, :publication_date, :category, :author, photos: [])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]


  def index
    @articles = policy_scope(Article.all).order(publication_date: :desc)
  end

  def show
    @article = authorize Article.find(params[:id])
    @four_last_articles = Article.last(4)
    @lead = Lead.new
  end

  # def new
  #   @article = authorize Article.new
  # end

  # def create
  #   @article = authorize Article.new(article_params)
  #   if @article.save
  #     redirect_to @article
  #   else
  #     render :new, status: :unprocessable_entity, alert: "Article not created #{article.errors.full_messages}"
  #   end
  # end

  private 

  def article_params
    params.require(:article).permit(:title, :content, :publication_date, :category, :author, photos: [])
  end
end

app/views/admin/articles/_form.html.erb
<div class="admin-new-page-container">
  <% if @article.new_record? %>
    <h1>Ajouter un article</h1>
  <% else %>
    <h1>Modifier un article</h1>
  <% end %>

  <%= link_to admin_articles_path, class: "mb-16px" do %>
    <i class="fas fa-arrow-left"></i> Retour
  <% end %>


<div class="admin-new-page-container__form_container">
    <%= simple_form_for [:admin, @article] do |f| %>
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <p><%= pluralize(@article.errors.count, "erreur") %>  Merci de vérifier les champs </p>

          <ul>
            <% @article.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-inputs">
        <%= f.input :title, label: "Titre" %>
        <%= f.input :intro_text, label: "Introduction", as: :text %>
        <%= f.input :category, label: "Categorie" %>
      </div>

      <div class="two_inputs_row">
          <%= f.input :author, label: "Auteur" %>
          <%= f.input :publication_date, type: :date, html5: true  %>
      </div>
      <div class="form-inputs mt-12px">
        <%= f.rich_text_area :content %>
      </div>

      <%= f.input :photos, as: :file, label: "Miniature de l'offre", input_html: { multiple: true } %>

      <div class="flex justify-center mt-16px"></div>
        <%= f.submit "Enregistrer", class: 'btn btn--dark mb-5' %>
      </div>           
    <% end %> 
  </div>
</div>

app/views/admin/articles/edit.html.erb
<%= render "admin/articles/form" %>

app/views/admin/articles/index.html.erb
<div class="admin-index-container">
  <div class="header-container">
    <h1 class="header-title">Articles</h1>
    
    <div class="flex align-center space-between  w-100percent">
      <%= link_to new_admin_article_path(), class: "btn btn--icon" do %>
        <i class="fas fa-plus"></i> <!-- Plus icon -->
        Rédiger un nouvel article
      <% end %>
      <%= link_to admin_index_path() do %>
        <i class="fas fa-arrow-left"></i> <!-- Back arrow icon -->
        Retour
      <% end %>
    </div>

    <div class="search-container">
      <%= form_tag(admin_articles_path, method: :get, class: "search-form") do %>
        <%= text_field_tag(:search, params[:search], placeholder: "Rechercher un article par son titre", class: "search-input") %>
        <div class="flex">
          <%= submit_tag("Rechercher", class: "btn btn--dark") %>
          <% if params[:search].present? %>
            <%= link_to admin_articles_path, class: "btn btn--icon", method: :get do %>
              <i class="fas fa-sync-alt"></i>
              Réinitialiser
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="content-container">
    <table>
      <thead>
        <tr>
          <th>Titre</th>
          <th>Text intro</th>
          <th>Auteur</th>
          <th>Date de publication</th>
          <th></th> <!-- Added column for actions -->
          <th></th> <!-- Added column for actions -->
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td><%= article.title&.truncate(30) %></td>
            <td><%= article.intro_text&.truncate(30) %></td>
            <td><%= article.author %></td>
            <td><%= article.publication_date&.strftime("%d/%m/%Y") %></td>
            <td>
              <%= link_to admin_article_path(article), class: "btn btn--icon" do %>
                <i class="fas fa-eye"></i> <!-- Show button with eye icon -->
              <% end %>
              <%= link_to edit_admin_article_path(article), class: "btn btn--icon" do %>
                <i class="fas fa-pencil-alt"></i> <!-- Edit button with pencil icon -->
              <% end %>
            </td>
            <td>             
              <%= link_to admin_article_path(article), method: :delete, data: { turbo_method: :delete } do %>
                <i class="fas fa-trash"></i> <!-- Delete button with trash icon -->
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>

app/views/admin/articles/new.html.erb
<%= render "admin/articles/form", article: @article %>

app/views/admin/articles/show.html.erb
<div class="admin-show-page-container">
  <h1><%= @article.title %></h1>
  <%= link_to 'Edit', edit_admin_article_path(@article) %> |
<%= link_to 'Retour', admin_articles_path %>
  <p><strong>Auteur:</strong> <%= @article.author %></p>
  <p><strong>Date de publication:</strong> <%= @article.publication_date %></p>
  <p><strong>Categorie</strong>: <%= @article.category %></p>
  <p><strong>Contenu:</strong>
    <div class="article-content">
      <%= @article.content %>
    </div>
  </p>
  <p><strong>Lien:</strong> <%= @article.link %></p>
  <p><strong>Texte d'introduction:</strong> <%= @article.intro_text %></p>

  <% if @article.photos.attached? %>
    <div class="photos">
      <% @article.photos.each do |photo| %>
        <%= image_tag photo %>
      <% end %>
    </div>
  <% end %>
</div>