config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "mentions_legales", to: "pages#mentions_legales"

  resources :leads, only: [:create]

  resources :admin, only: [:index], controller: "admin/dashboard"
  resources :articles, only: [:index, :show]


  namespace :admin do 
    resources :leads, only: [:index, :new, :create, :edit, :update, :show, :destroy]
    resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :testimonies, only: [:index, :show, :new, :create, :destroy, :edit, :update]
    resources :trusted_customers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end 
end

app/models/lead.rb
class Lead < ApplicationRecord
  TYPES = ["Un étudiant ou doctorant", "Une société publique ou privée", "Un organisme de formation"]

  validates :last_name, :first_name, :email, :message, presence: true
  # validates :terms, inclusion: [true]
  validates :email, :format => { :with => %r{.+@.+\..+} }, allow_blank: true

  validates :customer_type, presence: true, inclusion: { in: TYPES }

  def self.ransackable_attributes(auth_object = nil)
    ["company", "created_at", "customer_type", "email", "first_name", "id", "last_name", "message", "newsletter", "phone_number", "terms", "updated_at"]
  end
end

app/controllers/admin/leads_controller.rb
class Admin::LeadsController < Admin::DashboardController
  def index
    if params[:search]
      @leads = Lead.where("first_name ILIKE ? OR last_name ILIKE ? OR email ILIKE ? OR phone_number ILIKE ? OR message ILIKE ? OR company ILIKE ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    else
      @leads = Lead.all
    end
  end

  def show
    @lead = Lead.find(params[:id])
  end

  def new
    @lead = Lead.new
  end

  def create
    @lead = Lead.new(lead_params)

    if @lead.save
      redirect_to admin_leads_path, notice: "Lead créé avec succès."
    else
      render :new, alert: "Veuillez vérifier les erreurs ci-dessous #{@lead.errors.full_messages}", status: :unprocessable_entity
    end
  end

  def edit
    @lead = Lead.find(params[:id])
  end

  def update
    @lead = Lead.find(params[:id])

    if @lead.update(lead_params)
      redirect_to admin_leads_path, notice: "Lead modifié avec succès."
    else
      render :edit, alert: "Veuillez vérifier les erreurs ci-dessous.", status: :unprocessable_entity
    end
  end

  def destroy
    @lead = Lead.find(params[:id])
    @lead.destroy

    redirect_to admin_leads_path, notice: "Lead supprimé avec succès."
  end

  private

  def lead_params
    params.require(:lead).permit(:first_name, :last_name, :email, :phone_number, :message, :company, :customer_type)
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create]
  invisible_captcha only: [:create], on_spam: :spam_call_back_redirection

  def create
    @lead = authorize Lead.new(lead_params)
    if @lead.save
      flash[:notice] = "Votre demande a bien été prise en compte, merci !"
      redirect_to root_path
    else
      render "pages/home", alert: "Veuillez remplir tous les champs"
    end
  end

  private 

  def lead_params
    params.require(:lead).permit(:first_name, :last_name, :email, :phone_number, :company, :customer_type, :message)
  end

  def spam_call_back_redirection
    flash[:alert] = "Merci"
    redirect_to root_path
  end
end

app/views/admin/leads/_form.html.erb
<div class="admin-new-page-container">
    <% if @lead.persisted? %>
      <h1>Modifier un lead</h1>
    <% else %>
      <h1>Ajouter un lead</h1>
    <% end %>

  <%= link_to admin_leads_path, class: "mb-16px" do %>
    <i class="fas fa-arrow-left"></i> Retour
  <% end %>

<div class="admin-new-page-container__form_container">
    <%= simple_form_for [:admin, @lead] do |f| %>
      <% if @lead.errors.any? %>
        <div id="error_explanation">
          <p class="red-error"><%= pluralize(@lead.errors.count, "erreur") %>. Merci de vérifier les champs </p>

          <ul>
            <% @lead.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="two_inputs_row">
        <%= f.input :first_name, label: "Prénom", placeholder: "Alan" %>
        <%= f.input :last_name, label: "Nom", placeholder: "Turing" %>
      </div>
      <div class="two_inputs_row">
        <%= f.input :email, label: "Email", placeholder: "alan.turing@enigma.com" %>
        <%= f.input :phone_number, label: "Téléphone", placeholder: "+33 1 23 45 67 89" %>
      </div>

      <%= f.input :company, label: "Société", placeholder: "Société Enigma" %>
      <%= f.input :message, as: :text, placeholder: "Détaillez au mieux votre besoin." %>
      <%= f.input :customer_type, label: "Vous êtes...",
                  as: :radio_buttons,
                  collection_wrapper_tag: 'div',
                  collection_wrapper_class: 'category-wrapper-contact-form',
                  item_wrapper_class: 'category-item',
                  input_html: { class: 'category-selector' },
                  collection: Lead::TYPES,
                  item_label_class: 'radio-button-check'
                  %>

      <%= f.input :newsletter %>
      <div class="flex justify-center mt-16px">
        <%= f.submit "Envoyer", class: 'btn btn--dark mb-5' %>
      </div>           
    <% end %> 
  </div>
</div>

app/views/admin/leads/edit.html.erb
<%= render "admin/leads/form" %>

app/views/admin/leads/index.html.erb
<div class="admin-index-container">
  <div class="header-container">
    <h1 class="header-title">Leads</h1>

  <div class="flex align-center space-between  w-100percent">
    <%= link_to new_admin_lead_path(), class: "btn btn--icon" do %>
      <i class="fas fa-plus"></i> <!-- Plus icon -->
      Enregistrer un nouveau lead
    <% end %>
    <%= link_to admin_index_path() do %>
      <i class="fas fa-arrow-left"></i> <!-- Back arrow icon -->
      Retour
    <% end %>
  </div>


    <div class="search-container">
      <%= form_tag(admin_leads_path, method: :get, class: "search-form") do %>
        <%= text_field_tag(:search, params[:search], placeholder: "Rechercher un lead", class: "search-input") %>
        <div class="flex">
          <%= submit_tag("Rechercher", class: "btn btn--dark") %>
          <% if params[:search].present? %>
            <%= link_to admin_leads_path, class: "btn btn--icon", method: :get do %>
              <i class="fas fa-sync-alt"></i>
              Réinitialiser
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="content-container">
      <table>
        <thead>
          <tr>
            <th>Id</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Email</th>
            <th>Telephone</th>
            <th>Société</th>
            <th></th> 
            <th></th> 
          </tr>
        </thead>
        <tbody>
          <% @leads.each do |lead| %>
            <tr>
              <td><%= lead.id %></td>
              <td><%= lead.first_name %></td>
              <td><%= lead.last_name %></td>
              <td><%= lead.email %></td>
              <td><%= lead.phone_number %></td>
              <td><%= lead.company %></td>
              <td>
                <%= link_to admin_lead_path(lead), class: "btn btn--icon" do %>
                  <i class="fas fa-eye"></i> <!-- Show button with eye icon -->
                <% end %>
                <%= link_to edit_admin_lead_path(lead), class: "btn btn--icon" do %>
                  <i class="fas fa-pencil-alt"></i> <!-- Edit button with pencil icon -->
                <% end %>
            </td>
            <td>
              <%= link_to admin_lead_path(lead), method: :delete, data: { turbo_method: :delete } do %>
                <i class="fas fa-trash"></i> <!-- Delete button with trash icon -->
              <% end %>
            </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  </div>
</div>

app/views/admin/leads/new.html.erb
<%= render "admin/leads/form", lead: @lead %>

app/views/admin/leads/show.html.erb
<!-- FILEPATH: /Users/charliebertrand/code/Schwaips/projects/faham_v2/app/views/admin/articles/show.html.erb -->


<div class="admin-show-page-container">


<h1>Lead Details</h1>
<%= link_to 'Edit', edit_admin_lead_path(@lead) %> |
<%= link_to 'Retour', admin_leads_path %>

<p><strong>Name:</strong> <%= @lead.first_name %></p>
<p><strong>Email:</strong> <%= @lead.last_name %></p>
<p><strong>Phone:</strong> <%= @lead.phone_number %></p>
<p><strong>Société :</strong> <%= @lead.company %></p>
<p><strong>Type :</strong> <%= @lead.customer_type %></p>
<p><strong>Message :</strong> <%= @lead.message %></p>
<p><strong>Accepte la newsletter ? :</strong> <%= @lead.newsletter ? "Oui" : "Non" %></p>
<p><strong>Accepte les termes :</strong> <%= @lead.terms ? "Oui" : "Non"  %></p>

</div>
<!-- Add more lead details here as needed -->