config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "mentions_legales", to: "pages#mentions_legales"

  resources :leads, only: [:create]

  resources :admin, only: [:index], controller: "admin/dashboard"
  resources :articles, only: [:index, :show]


  namespace :admin do 
    resources :leads, only: [:index, :new, :create, :edit, :update, :show, :destroy]
    resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :testimonies, only: [:index, :show, :new, :create, :destroy, :edit, :update]
    resources :trusted_customers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end 
end

app/views/shared/_admin_navbar.html.erb
<aside class="sidebar">
  <ul>
    <li><%= link_to "Leads", admin_leads_path() %></li>
    <li><%= link_to "Articles", admin_articles_path() %></li>
    <li><%= link_to "Logo client", admin_trusted_customers_path() %></li>
    <li><%= link_to "Témoignage", admin_testimonies_path() %></li>
  </ul>
</aside>

app/views/shared/_css-cdn.html.erb
<link href="https://cdn.jsdelivr.net/npm/@splidejs/splide@4.1.4/dist/css/splide.min.css" rel="stylesheet">

app/views/shared/_flashes.html.erb
<p data-controller="flash" class="notice"><%= notice %></p>
<p data-controller="flash" class="alert"><%= alert %></p>


<!--
<% if notice %>
  <div class="alert alert-info" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning" role="alert">
    <%= alert %>
  </div>
<% end %>
-->

app/views/shared/_footer.html.erb
<div class="footer">
  <p>© 2021 Faham</p>
  <%= link_to "Mention Légales", "/mentions_legales" %>
  <p>Siret: 89504842900016 RCS Saint Pierre</p>
</div>

app/views/shared/_meta.html.erb
<title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
 <meta property="og:title" content="<%= meta_title %>" />
 <meta property="og:type" content="website" />
 <meta property="og:url" content="<%= request.original_url %>" />
 <meta property="og:image" content="<%= meta_image %>" />
 <meta property="og:description" content="<%= meta_description %>" />
 <meta property="og:site_name" content="<%= meta_title %>" />

 <!-- Twitter Card data -->
 <meta name="twitter:card" content="summary_large_image">
 <!-- <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>"> -->
 <meta name="twitter:description" content="<%= meta_description %>">
 <!--- <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>"> -->
 <meta name="twitter:image:src" content="<%= meta_image %>">

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <%= link_to root_path do %>
    <%= show_svg "faham-logo.svg" %>
  <% end %>

  <div class="navbar-container__link-container">

    <%= link_to "Accueil", root_path, class:"#{"active" if is_root_path? }" %>
    <%#= link_to "Références scientifiques", root_path %>
    <%= link_to "Blog", articles_path, class:"#{"active" if is_blog_path? }" %>

    <% if user_signed_in? %>
      <% if current_user.admin %>
        <%= link_to "Admin", "/admin", class:"#{"active" if is_admin_path? }" %>
      <% end %>
      <%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete } %>
    <% end %>
  </div>
</div>


<div class="navbar-mobile-container">
  <div class="navbar-mobile-container__link-container">
  <%= link_to root_path, class:"navbar-mobile-container__link #{"active" if is_root_path?}" do %>
    <i class="fa-solid fa-house"></i>
    Accueil
  <% end %>
  
    <%#= link_to "Références scientifiques", root_path %>
  <%= link_to articles_path, class: "navbar-mobile-container__link #{"active" if is_blog_path?}" do %>
    <i class="fa-solid fa-book"></i>
    Blog
  <% end %>

  <% if user_signed_in? %>
    <% if current_user.admin %>
      <%= link_to "/admin", class: "navbar-mobile-container__link #{"active" if is_admin_path?}" do %>
        <i class="fa-solid fa-cog"></i>
        Admin
      <% end %>
    <% end %>
    <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "navbar-mobile-container__link" do %>
      <i class="fa-solid fa-sign-out"></i>
      
    <% end %>
  <% end %>



  </div>
  


</div>