config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "mentions_legales", to: "pages#mentions_legales"

  resources :leads, only: [:create]

  resources :admin, only: [:index], controller: "admin/dashboard"
  resources :articles, only: [:index, :show]


  namespace :admin do 
    resources :leads, only: [:index, :new, :create, :edit, :update, :show, :destroy]
    resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    resources :testimonies, only: [:index, :show, :new, :create, :destroy, :edit, :update]
    resources :trusted_customers, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end 
end

app/models/trusted_customer.rb
class TrustedCustomer < ApplicationRecord
  has_one_attached :photo

  def self.to_be_displayed
    TrustedCustomer.where(display: true)
  end
end

app/controllers/admin/trusted_customers_controller.rb
class Admin::TrustedCustomersController < Admin::DashboardController

  def index
    if params[:search]
      @trusted_customers = TrustedCustomer.where("title ILIKE ?", "%#{params[:search]}%")
    else
      @trusted_customers = TrustedCustomer.all
    end
  end

  def show
    @trusted_customer = TrustedCustomer.find(params[:id])
  end

  def new
    @trusted_customer = TrustedCustomer.new
  end

  def create
    @trusted_customer = TrustedCustomer.new(trusted_customer_params)
    if @trusted_customer.save
      redirect_to admin_trusted_customers_path, notice: "Succès"
    else
      render :new, alert: "Erreur", status: :unprocessable_entity
    end
  end

  def edit
    @trusted_customer = TrustedCustomer.find(params[:id])
  end

  def update
    @trusted_customer = TrustedCustomer.find(params[:id])
    if @trusted_customer.update(trusted_customer_params)
      redirect_to admin_trusted_customers_path, notice: "Succès"
    else
      render :edit, alert: "Erreur", status: :unprocessable_entity
    end
  end

  def destroy
    @trusted_customer = TrustedCustomer.find(params[:id])
    @trusted_customer.destroy
    redirect_to admin_trusted_customers_path, notice: "Succès"
  end


  private 


  def trusted_customer_params
    params.require(:trusted_customer).permit(:title, :photo, :display)
  end
end

app/views/admin/trusted_customers/_form.html.erb
<div class="admin-new-page-container">
  <% if @trusted_customer.new_record? %>
    <h1>Ajouter un logo</h1>
  <% else %>
    <h1>Modifier un logo</h1>
  <% end %>

  <%= link_to admin_trusted_customers_path, class: "mb-16px" do %>
    <i class="fas fa-arrow-left"></i> Retour
  <% end %>


<div class="admin-new-page-container__form_container">
    <%= simple_form_for [:admin, @trusted_customer] do |f| %>
      <% if @trusted_customer.errors.any? %>
        <div id="error_explanation">
          <p><%= pluralize(@trusted_customer.errors.count, "erreur") %>  Merci de vérifier les champs </p>

          <ul>
            <% @trusted_customer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-inputs">
        <%= f.input :title, label: "Titre" %>
        <%= f.input :display, label: "Afficher dans la homepage? " %>
      </div>

      <%= f.input :photo, as: :file, label: "Image" %>

      <% if @trusted_customer.photo.attached? %>
        <p>Image actuel : </p>
        <div class="admin-single-photo-miniature mt-12px">
          <%= image_tag @trusted_customer.photo %>
        </div>
      <% end %>

      <div class="flex justify-center mt-16px"></div>
        <%= f.submit "Enregistrer", class: 'btn btn--dark mb-5' %>
      </div>           
    <% end %> 
  </div>
</div>

app/views/admin/trusted_customers/edit.html.erb
<%= render "admin/trusted_customers/form" %>

app/views/admin/trusted_customers/index.html.erb
<div class="admin-index-container">
  <div class="header-container">
    <h1 class="header-title">Logo client confiance</h1>
    
    <div class="flex align-center space-between  w-100percent">
      <%= link_to new_admin_trusted_customer_path(), class: "btn btn--icon" do %>
        <i class="fas fa-plus"></i> <!-- Plus icon -->
        Nouveau
      <% end %>
      <%= link_to admin_index_path() do %>
        <i class="fas fa-arrow-left"></i> <!-- Back arrow icon -->
        Retour
      <% end %>
    </div>

    <div class="search-container">
      <%= form_tag(admin_trusted_customers_path, method: :get, class: "search-form") do %>
        <%= text_field_tag(:search, params[:search], placeholder: "Rechercher par titre", class: "search-input") %>
        <div class="flex">
          <%= submit_tag("Rechercher", class: "btn btn--dark") %>
          <% if params[:search].present? %>
            <%= link_to admin_trusted_customers_path, class: "btn btn--icon", method: :get do %>
              <i class="fas fa-sync-alt"></i>
              Réinitialiser
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="content-container">
    <table>
      <thead>
        <tr>
          <th>Titre</th>
          <th>Date de création</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @trusted_customers.each do |trusted_customer| %>
          <tr>
            <td><%= trusted_customer.title %></td>
            <td><%= trusted_customer.created_at.strftime("%d/%m/%Y - %H:%M") %></td>
            <td>
              <%= link_to admin_trusted_customer_path(trusted_customer), class: "btn btn--icon" do %>
                <i class="fas fa-eye"></i> <!-- Show button with eye icon -->
              <% end %>
              <%= link_to edit_admin_trusted_customer_path(trusted_customer), class: "btn btn--icon" do %>
                <i class="fas fa-pencil-alt"></i> <!-- Edit button with pencil icon -->
              <% end %>
            </td>
            <td>             
              <%= link_to admin_trusted_customer_path(trusted_customer), method: :delete, data: { turbo_method: :delete } do %>
                <i class="fas fa-trash"></i> <!-- Delete button with trash icon -->
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>

app/views/admin/trusted_customers/new.html.erb
<%= render "admin/trusted_customers/form" %>

app/views/admin/trusted_customers/show.html.erb
<div class="admin-show-page-container">
  <h1><%= @trusted_customer.title %></h1>
  <%= link_to 'Edit', edit_admin_trusted_customer_path(@trusted_customer) %> |
  <%= link_to 'Retour', admin_trusted_customers_path %>
  

  <p><strong>Titre:</strong> <%= @trusted_customer.title %></p>
  <p><strong>Afficher dans la homepage?:</strong> <%= @trusted_customer.display ? "Oui" : "Non" %></p>
  <% if @trusted_customer.photo.attached? %>
    <div class="photos">
      <%= image_tag @trusted_customer.photo %>
    </div>
  <% end %>
</div>